module led_disp(
	clk,
	rst_n,
	data,
	led_pwm);

	//---Ports declearation: generated by Robei---
	input clk;
	input rst_n;
	input [7:0] data;
	output led_pwm;

	wire clk;
	wire rst_n;
	wire [7:0] data;
	wire led_pwm;

	//----Code starts here: integrated by Robei-----
	reg  [12:0]  period_cnt ;      //周期计数器频率：10000Hz 周期:0.1ms  计数值:0.1ms*50MHz=5000
	reg  [12:0]  duty_cycle ;     //占空比数值
	
	assign   led_pwm = (period_cnt >= duty_cycle) ?  1'b0  :  1'b1;
	
	always @(posedge clk or negedge rst_n) begin
	    if(rst_n == 1'b0)
		    period_cnt <= 13'd0;
	    else if(period_cnt == 13'd5000)
		    period_cnt <= 13'd0;
		else
		    period_cnt <= period_cnt + 1'b1;
	end
	
	always @(posedge clk or negedge rst_n)begin
		if (rst_n == 1'b0)
			duty_cycle <= 13'd0;
		else begin
	 		if(data < 8'd10)             //光照强度(0,10)lux,占空比90% 
				duty_cycle <= 13'd3000;
			else if(data < 8'd100)       //光照强度(10,100)lux,占空比80%
				duty_cycle <= 13'd1750;
			else if(data < 8'd200)       //光照强度(100,200)lux,占空比60%
				duty_cycle <= 13'd1000;            
	        else                          //光照强度(200,255)lux,占空比40%
				duty_cycle <= 13'd500;
		end
	end
endmodule    //led_disp

